name: Daily Run main.py

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all files for debug
        run: |
          echo "当前目录文件列表："
          ls -al

      - name: Print working directory
        run: pwd

      - name: Display list.txt content
        run: |
          echo "======= list.txt ======="
          cat list.txt || echo "list.txt 文件未找到！"

      - name: Install dependencies
        run: pip install requests

      - name: Run main.py and show results
        run: |
          python main.py
          echo "======= Links used (from list.txt, no comments) ======="
          grep -v '^\s*#' list.txt | grep -v '^\s*$' || true
          echo "======= Output after replacement (output.txt) ======="
          cat output.txt
