name: Daily Run main.py

on:
  schedule:
    - cron: '0 0 * * *' # 每天世界标准时间0点运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Display list.txt content
        run: |
          echo "======= list.txt ======="
          cat list.txt
      - name: Run main.py and show results
        run: |
          python main.py
          echo "======= Links used (from list.txt, no comments) ======="
          grep -v '^\s*#' list.txt | grep -v '^\s*$' || true
          echo "======= Output after replacement (output.txt) ======="
          cat output.txt
